# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2934)
$foreground = rgb(E8B4D4)
$color0 = rgb(4F4E5A)
$color1 = rgb(131C45)
$color2 = rgb(131C45)
$color3 = rgb(131C45)
$color4 = rgb(171C47)
$color5 = rgb(57275E)
$color6 = rgb(8E2063)
$color7 = rgb(D68CB9)
$color8 = rgb(956282)
$color9 = rgb(19255C)
$color10 = rgb(19255C)
$color11 = rgb(19255C)
$color12 = rgb(1F265E)
$color13 = rgb(74347D)
$color14 = rgb(BD2A84)
$color15 = rgb(D68CB9)
