# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8B4D4
background         #2A2934
cursor             #806D98

active_tab_foreground     #2A2934
active_tab_background     #E8B4D4
inactive_tab_foreground   #E8B4D4
inactive_tab_background   #2A2934

active_border_color   #E8B4D4
inactive_border_color #2A2934
bell_border_color     #131C45

color0      #4F4E5A
color1		#131C45
color2		#131C45
color3		#131C45
color4		#171C47
color5		#57275E
color6		#8E2063
color7		#D68CB9
color8		#956282
color9		#19255C
color10		#19255C
color11		#19255C
color12		#1F265E
color13		#74347D
color14		#BD2A84
color15		#D68CB9
